// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBolzVBc_yzjRgfuWD58LbPjEYXynJpU7Y',
    appId: '1:891171695332:web:0589759b701a1e998edaf1',
    messagingSenderId: '891171695332',
    projectId: 'uniweek-ba04e',
    authDomain: 'uniweek-ba04e.firebaseapp.com',
    storageBucket: 'uniweek-ba04e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdSA9bWXg5DO2rk_29CDWuRe36EHNb9k8',
    appId: '1:891171695332:android:de720961805b6b1b8edaf1',
    messagingSenderId: '891171695332',
    projectId: 'uniweek-ba04e',
    storageBucket: 'uniweek-ba04e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Iz6oKCF-6-Va8gwMmJTtIqJdQkpMX5I',
    appId: '1:891171695332:ios:81d59729ec4582c38edaf1',
    messagingSenderId: '891171695332',
    projectId: 'uniweek-ba04e',
    storageBucket: 'uniweek-ba04e.firebasestorage.app',
    iosBundleId: 'com.example.uniWeek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Iz6oKCF-6-Va8gwMmJTtIqJdQkpMX5I',
    appId: '1:891171695332:ios:81d59729ec4582c38edaf1',
    messagingSenderId: '891171695332',
    projectId: 'uniweek-ba04e',
    storageBucket: 'uniweek-ba04e.firebasestorage.app',
    iosBundleId: 'com.example.uniWeek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBolzVBc_yzjRgfuWD58LbPjEYXynJpU7Y',
    appId: '1:891171695332:web:d63d0fab01b670038edaf1',
    messagingSenderId: '891171695332',
    projectId: 'uniweek-ba04e',
    authDomain: 'uniweek-ba04e.firebaseapp.com',
    storageBucket: 'uniweek-ba04e.firebasestorage.app',
  );
}
